Patch form reference on form-associated elements
webcomponents/shadydom pull request #221
Opened 2018-04-02 16:55 UTC by TimvdLippe

This does not include the `img` element, per https://github.com/whatwg/html/issues/294#issuecomment-377975277 The full list is available at https://html.spec.whatwg.org/multipage/forms.html#form-associated-element but it also includes `<option>` per https://html.spec.whatwg.org/multipage/form-elements.html#dom-option-form
### Reference Issue
Fixes #214

2018-04-02 19:19 UTC, TimvdLippe commented
Suddenly EVERY single IE11 test decided to fail 😭

2018-04-03 17:51 UTC, sorvell requested changes

2018-04-03 17:51 UTC, sorvell commented on src/patch-accessors.js
> +      const root = utils.ownerShadyRootForNode(this);
I think this should just be `this.getRootNode()`

2018-04-03 17:51 UTC, sorvell commented on src/patch-builtins.js
> +    // See https://html.spec.whatwg.org/multipage/forms.html#form-associated-element
This won't work on browser on which we cannot patch prototypes (Safari 9 and older Chrome). This may be ok but it at least deserves a comment.

2018-04-03 17:51 UTC, sorvell commented on src/patch-accessors.js
> +const FormAssociatedAccessors = {
We also need to fix <form> element so that it doesn't act on elements that are not in the same root.

2018-04-14 17:27 UTC, TimvdLippe commented
Updated to now also patch `<form>` (except on Safari 9, which has `configurable: false` :cry: )

2018-05-17 18:08 UTC, sorvell requested changes
We need to ensure that the `<form>` also does not act on elements not in the elements list, like when it gets `reset` or `submit`'d.

Without addressing this, the changes here may not be worth doing since half-polyfilling may be more confusing than simply not polyfilling the behavior and noting the limitation.

2018-05-19 14:55 UTC, TimvdLippe commented
@sorvell I have fixed `reset`, but `submit` is significantly more difficult. The algorithm is an absolute beast (https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-form-submit) and it provides no point for us to modify the list of elements. Not sure what our options are for that function, other than completely reimplementing it?

2018-05-29 18:14 UTC, TimvdLippe commented
Talked in our meeting about this. Conclusion: we need to fully polyfill `submit` or this will only make matters worse. To do so, we have a couple of options:

1. Create a separate form element, copy the correct elements in there and submit that one
2. Disable all elements that should not be submitted and enable them afterwards
3. Remove elements from the DOM temporarily

Step 2 and 3 have observable effects, so we have to try 1 first, but that might not be 100% compliant. We have to see.

2018-06-02 18:28 UTC, TimvdLippe commented
@sorvell `submit` polyfilled :tada:

2018-08-03 21:01 UTC, TimvdLippe commented
@sorvell Do we still want to move forward with this PR or do you think it is unlikely to ever land? In that case, let's not waste more time and simply document it as a known limitation.

2019-06-10 20:04 UTC, azakus commented
I think we'll just leave this as a known limitation.

2019-06-10 20:04 UTC, closed without merging