Fix dispatching event from ShadowRoot
webcomponents/shadydom pull request #322
Opened 2019-03-04 19:15 UTC by azakus

Fixes #321

### Reference Issue

2019-03-04 19:16 UTC, TimvdLippe approved these changes

2019-03-05 18:01 UTC, sorvell commented on src/patches/ShadowRoot.js
> +  dispatchEvent(event) {
An event listener on the shadowRoot needs to hear the event.

2019-03-05 18:02 UTC, sorvell requested changes
In addition to this change, we need to make sure event listeners on the shadowRoot itself hear the event.

2019-06-10 19:44 UTC, azakus commented
Remaking in the polyfill monorepo.

2019-06-10 19:44 UTC, closed without merging